name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Lint project
        run: npm run lint
